### ISSUE TITLE
Forward cannot be used in a method that also uses return

### ISSUE THREAD

**Issue by kikofernandez** [parapluu/encore#845] opened 2017-07-04 12:12 UTC
It seems like forward cannot be used in a method that also uses `return`. This example compiles to C raising an error:

```ruby
active class B
  var x: String = "hola"
  def test(): (int, int)
    (3, 4)
  end
end

active class Main
  def test(): (int, int)
    val b = new B
    if true then
      return (3, 4)
    else
      forward(b!test())
    end
  end

  def main(): unit
    ()
  end
end
```

Error message:
```
encorec test.enc
test_src/Main.encore.c:264:5: error: void function '_enc__method__test_Main_test_async' should not return a value
      [-Wreturn-type]
    return _tuple_6;
    ^      ~~~~~~~~
1 error generated.
 *** Compilation failed with exit code 1 ***

```

**Comment by supercooldave** [comment] 2017-07-04 12:14
Duplicate of #816.
If something written here is new, add it to the previous issue.

**Closed as completed by supercooldave** 2017-07-04 12:14 UTC
