### ISSUE TITLE
Closure's body does not create the future by async method call

### ISSUE THREAD

**Issue by PhucVH888** [parapluu/encore#806] opened 2017-05-16 09:03 UTC
Closure does not create the future that is created by asynchronous method call in its body.
```
active class Main
  def main() : unit
    val fres = (fun (x : int) : Fut[int] => this ! inc(x))
    println("{}", get(fres(42)))
  end

  def foo() : int
    10
  end

  def inc(x : int) : int
    x + 1
  end
end
```
The issue won't happen if the `await()` is used.
```
    ...
  def main() : unit
    val fres = (fun (x : int) : Fut[int] => this ! inc(x))
    val t = fres(42)
    await(t)
    println("{}", get(t))
  end
    ...
```

**Comment by EliasC** [comment] 2017-05-16 09:24
I don't understand what is the problem here. Looking at the generated code for the closure, the future seems to be created just fine:
```
static value_t _enc__closure_fun_closure0(pony_ctx_t** _ctx, pony_type_t** runtimeType, value_t _args[], void* _env)
{
  ENC_DTRACE1(CLOSURE_ENTRY, (uintptr_t)*_ctx);
  int64_t _enc__arg_x = (_args[0]).i;
  _enc__active__bug_Main_t* _enc__field_this = (*((struct _enc__env_closure0*) _env))._enc__field_this;
  check_receiver(_enc__field_this, " ! ", "this", "inc", "\"bug.enc\" (line 8, column 49)");
  pony_type_t* _tmp_0[] = {};
  future_t* _fut_1 = _enc__method__bug_Main_inc_future(_ctx, _enc__field_this, NULL, _enc__arg_x);
  int64_t _tmp_2 = future_get_actor(_ctx, _fut_1).i;
  ENC_DTRACE1(CLOSURE_EXIT, (uintptr_t)*_ctx);
  return ((encore_arg_t) {.i = _tmp_2});
}
```
(the call to `_enc__method__bug_Main_inc_future` is where the future is created). 

However, the program will deadlock as it has an actor blocking on a future which the actor itself is supposed to fulfill. When using `await`, you let the actor handle other messages before continuing, so the deadlock is avoided.

**Comment by supercooldave** [comment] 2017-05-16 09:34
The problem is deadlock, as you say. We worked that out a little later.

**Comment by EliasC** [comment] 2017-05-17 07:26
I don't think this is an Encore bug. If you cause a deadlock, your program will deadlock.

**Comment by PhucVH888** [comment] 2017-05-17 08:10
@EliasC I see. I thought it was a bug. The fix is no longer necessary, and discarded soon.

**Comment by supercooldave** [comment] 2017-06-08 13:28
Closing, as this was not a bug.

**Closed as completed by supercooldave** 2017-06-08 13:28 UTC
Labels: bug
